from . import test_smoke
from . import test_bulk_idempotency
from . import test_second_run_changes_nothing
from . import test_company_scope
from . import test_conflict_identity
from . import test_ag_rel_verbatim
from . import test_warnings_render
from . import test_phase_registry
from . import test_camera_phase
from . import test_site_phase
from . import test_background_run
from . import test_recalc_guard
from . import test_later_pass_finishes_the_job
from . import test_run_totals_survive_the_passes
from . import test_adoption_of_auto_hardware
from . import test_leaves_phase
from . import test_source_refuses_a_field
from . import test_tours
